/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import java.sql.Connection;
import util.ConnectionFactory;

public class Main {

    public static void main(String[] args) {
         
        Connection c = ConnectionFactory.getConnection();
        
    }
}
