/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import java.util.Scanner;
import model.Project;

public class Main extends Project{

    public static void main(String[] args) {
         
        
    }
}
