/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
         
        
    }
}
